{
 "title": "OTUS-SoNet",
 "tags": [ "sonet" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "DB latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "database_processing_time_summary_ms{job=\"otus-sonet\", target=\"query\"}",
     "legendFormat": "{{table}}:{{target}}:quantile={{quantile}}"
    }
   ]
  },
  {
   "title": "Время обработки запроса user/search в мс для 90 перцентиля (latency)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "request_processing_time_summary_ms{status=\"200\"}",
     "legendFormat": "quantile={{quantile}}:{{url}}"
    }
   ]
  },
  {
   "title": "Успешные запросы в сек (throughput)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(request_processing_time_summary_ms_count[1m])",
     "legendFormat": "{{status}}:url={{url}}"
    }
   ]
  },
  {
   "title": "Кол-во активных потоков обработки в приложении (goroutins)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"otus-sonet\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}