version: '3.9'
services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    network_mode: "host"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=recordings
      - MYSQL_TCP_PORT=3306

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
